# Generated by Django 2.1.3 on 2018-12-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelisting',
            name='date_invalidated',
            field=models.DateField(null=True),
        ),
    ]
