# Generated by Django 2.1.2 on 2018-12-20 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181220_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopTags',
            new_name='ShopTag',
        ),
    ]
