# Generated by Django 2.1.4 on 2018-12-21 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_auto_20181202_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pricelisting',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='pricelisting',
            name='store_name',
        ),
        migrations.RemoveField(
            model_name='pricelisting',
            name='user_name',
        ),
        migrations.AddField(
            model_name='pricelisting',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pricelisting',
            name='date_inserted',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pricelisting',
            name='date_invalidated',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pricelisting',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Product'),
        ),
        migrations.AddField(
            model_name='pricelisting',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Shop'),
        ),
    ]
