# Generated by Django 2.1.4 on 2018-12-22 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_auto_20181221_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PriceListing',
            new_name='prices',
        ),
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productplaceholder'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shopplaceholder'),
        ),
    ]
