# Generated by Django 2.1.4 on 2018-12-22 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20181222_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.productplaceholder'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.shopplaceholder'),
        ),
    ]
