# Generated by Django 2.1.5 on 2019-02-25 00:53

import django.contrib.gis.db.models.fields
from django.db import migrations
import project.api.models.shop


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190103_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, validators=[project.api.models.shop.coordinates_validator]),
        ),
    ]
