# Generated by Django 2.1.7 on 2019-02-27 21:08

from django.db import migrations, models
import project.api.models.price


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190225_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='date_from',
            field=models.DateField(default=project.api.models.price.datetime_now),
        ),
        migrations.AlterField(
            model_name='price',
            name='date_to',
            field=models.DateField(default=project.api.models.price.datetime_oneyearfromnow),
        ),
    ]
